# Alemão
curl https://sumtube.io/de/Brz1R-d1tD0
sleep 15
curl https://sumtube.io/de/AqazlmVVAEM
sleep 15
curl https://sumtube.io/de/BqD1VdJTAU0
sleep 15
curl https://sumtube.io/de/89i4XQnF_xQ
sleep 15
curl https://sumtube.io/de/TreGXIv63ps
sleep 15

# Japonês
curl https://sumtube.io/ja/Rl9Gz1Yf6wM
sleep 15
curl https://sumtube.io/ja/8dKBH4x0D9o
sleep 15
curl https://sumtube.io/ja/97h2Zj5p_k4
sleep 15
curl https://sumtube.io/ja/97h2Zj5p_k4
sleep 15
curl https://sumtube.io/ja/97h2Zj5p_k4
sleep 15

# Russo
curl https://sumtube.io/ru/Z8JvwqefT_w
sleep 15
curl https://sumtube.io/ru/33n4vfkdmnM
sleep 15
curl https://sumtube.io/ru/nS_IsgnhMu4
sleep 15
curl https://sumtube.io/ru/Z2KgOe3pW-8
sleep 15
curl https://sumtube.io/ru/2oqWl6H3vWM
sleep 15

# Árabe
curl https://sumtube.io/ar/vMiRBLU8HeU
sleep 15
curl https://sumtube.io/ar/MNv-MzO-lEU
sleep 15
curl https://sumtube.io/ar/ZFFK-xfCpt4
sleep 15
curl https://sumtube.io/ar/IDKFrbYtBz4
sleep 15
curl https://sumtube.io/ar/2oqWl6H3vWM
sleep 15

# Chinês
curl https://sumtube.io/zh/Rl9Gz1Yf6wM
sleep 15
curl https://sumtube.io/zh/8dKBH4x0D9o
sleep 15
curl https://sumtube.io/zh/RwZaXl1yBUE
sleep 15
curl https://sumtube.io/zh/97h2Zj5p_k4
sleep 15
curl https://sumtube.io/zh/97h2Zj5p_k4
sleep 15

# Coreano
curl https://sumtube.io/ko/Rl9Gz1Yf6wM
sleep 15
curl https://sumtube.io/ko/8dKBH4x0D9o
sleep 15
curl https://sumtube.io/ko/RwZaXl1yBUE
sleep 15
curl https://sumtube.io/ko/97h2Zj5p_k4
sleep 15
curl https://sumtube.io/ko/97h2Zj5p_k4
sleep 15
