services:
  go-server:
    build: ./api
    container_name: go-server
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - ./api/.env
    environment:
      - PATH=/usr/local/bin:${PATH}

  renderer-server:
    build: ./renderer
    container_name: renderer-server
    ports:
      - "8081:8081"
    networks:
      - app-network
    env_file:
      - ./renderer/.env
    environment:
      - PATH=/usr/local/bin:${PATH}

  youtube-metadata-server:
    build: ./youtube-metadata
    container_name: youtube-metadata-server
    ports:
      - "6060:6060"
    networks:
      - app-network
    env_file:
      - ./youtube-metadata/.env
    environment:
      - PATH=/usr/local/bin:${PATH}

  youtube-transcript-py-server:
    build: ./youtube-transcript-py
    container_name: youtube-transcript-py-server
    ports:
      - "5050:5050"
    networks:
      - app-network
    env_file:
      - ./youtube-transcript-py/.env
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - ./nginx/.env
    volumes:
      - ./api/nginx/api.conf.template:/etc/nginx/conf.d/api.conf.template
      - ./renderer/nginx/renderer.conf.template:/etc/nginx/conf.d/renderer.conf.template
      - ./youtube-transcript-py/nginx/transcript-py.conf.template:/etc/nginx/conf.d/transcript-py.conf.template
      - ./youtube-metadata/nginx/youtube-metadata.conf.template:/etc/nginx/conf.d/youtube-metadata.conf.template
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./renderer/static:/app/static
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /dev/null:/etc/nginx/conf.d/default.conf
    entrypoint: ["/docker-entrypoint.sh"]
    depends_on:
      - go-server
      - renderer-server
      - youtube-transcript-py-server
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./renderer/static:/app/static
    entrypoint: >
      sh -c "if [ \"$ENABLE_HTTPS\" = 'true' ]; then
        certbot certonly --webroot -w /app/static -d sumtube.io -d api.sumtube.io --email you@email.com --agree-tos --non-interactive;
      else
        echo 'Skipping certbot (dev mode)';
      fi"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
