services:
  go-server:
    build: ./api
    container_name: go-server
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - ./api/.env
    environment:
      - PATH=/usr/local/bin:${PATH}

  renderer-server:
    build: ./renderer
    container_name: renderer-server
    ports:
      - "8081:8081"
    networks:
      - app-network
    env_file:
      - ./renderer/.env
    environment:
      - PATH=/usr/local/bin:${PATH}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - ./nginx/.env # 👈 use unified env file
    volumes:
      - ./api/nginx/api.conf.template:/etc/nginx/conf.d/api.conf.template
      - ./renderer/nginx/renderer.conf.template:/etc/nginx/conf.d/renderer.conf.template
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./renderer/static:/app/static
      - /dev/null:/etc/nginx/conf.d/default.conf
    entrypoint: ["/docker-entrypoint.sh"]
    depends_on:
      - go-server
      - renderer-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
