name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ vars.VPS_HOST }}
          USER: ${{ vars.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          HOST: ${{ vars.VPS_HOST }}
          USER: ${{ vars.VPS_USER }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes $USER@$HOST << 'EOF'
            echo "✅ Connected to VPS"
            cd /home/$USER/sumtube
            git pull origin main
            cd BE
            chmod +x start.sh
            ./start.sh up
          EOF
