name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 --decode > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Debug SSH key
        run: |
          echo "----- First 5 lines of SSH key -----"
          head -n 5 ~/.ssh/id_ed25519
          echo "----- Last 3 lines of SSH key -----"
          tail -n 3 ~/.ssh/id_ed25519
          echo "----- Key file info -----"
          ls -l ~/.ssh/id_ed25519
          sha256sum ~/.ssh/id_ed25519 || shasum -a 256 ~/.ssh/id_ed25519
        shell: bash

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }} "echo '✅ SSH connection successful!'"
        shell: bash

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key_path: ~/.ssh/id_ed25519
          port: 22
          script: |
            echo "✅ Connected to VPS"
            cd /home/${{ vars.VPS_USER }}/sumtube
            git pull origin main
            cd BE
            chmod +x start.sh
            ./start.sh up
