name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to VPS using password
        env:
          HOST: ${{ vars.VPS_HOST }}
          USER: ${{ vars.VPS_USER }}
          PASSWORD: ${{ secrets.VPS_SSH_PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            echo "✅ Connected to VPS with password"
            cd /home/$USER/sumtube
            git pull origin main
            cd BE
            chmod +x start.sh
            ./start.sh up
          EOF
