name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to VPS using password
        env:
          HOST: ${{ vars.VPS_HOST }}
          USER: ${{ vars.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 $HOST >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            echo "✅ Connected to VPS with password"
            cd /home/$USER/sumtube
            git pull origin main
            cd BE
            chmod +x start.sh
            ./start.sh up
          EOF
